name: Build PDF

on:
  workflow_dispatch:

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Build docker images
      run: docker build -t local docker/Dockerfile
